font_family      family='JetBrainsMono Nerd Font'
font_size 16.5
text_composition_strategy legacy
window_padding_width 2

underline_hyperlinks never
disable_ligatures always
# color
include themes/silence.conf
background_opacity 0.96
# cursor
cursor_blink_interval 0
# --> cursor trail
cursor_trail 1
cursor_trail_start_threshold 0
cursor_trail_decay 0.001 0.18
# performance tuning
repaint_delay 16
input_delay 5
# window layout
remember_window_size  no
placement_strategy center
hide_window_decorations yes
confirm_os_window_close 0
# advanced
shell_integration no-cursor
term xterm-kitty
allow_remote_control yes
listen_on unix:/tmp/kitty
enable_audio_bell no
clipboard_control write-clipboard write-primary read-clipboard read-primary
# keyboard shortcuts
map ctrl+shift+,   load_config_file
map ctrl+shift+t   launch --type=background ~/.config/kitty/scripts/toggle_cursor_trail.sh
map ctrl+shift+f   launch --type=background ~/.config/kitty/scripts/toggle_font_size.sh
