font_family      family='IosevkaTerm Nerd Font'
font_size 17
modify_font cell_width 0px
modify_font cell_height -2px

font_family      family='DroidSansM Nerd Font'
font_size 16
modify_font cell_width -1px
modify_font cell_height 0px

font_family      family='Px437 IBM VGA 8x16'
font_size 18
modify_font cell_width 0px
modify_font cell_height 1px

# =================================================
text_composition_strategy legacy
underline_hyperlinks never
disable_ligatures always
# color
include themes/silence.conf
background_opacity 1.0
# performance tuning
repaint_delay 16
input_delay 5
# cursor
cursor_blink_interval 0
# --> cursor trail
cursor_trail 0
cursor_trail_start_threshold 0
cursor_trail_decay 0.001 0.18
# window layout
remember_window_size  no
hide_window_decorations yes
confirm_os_window_close 0
window_padding_width 0
# advanced
shell_integration no-cursor
term xterm-kitty
placement_strategy bottom
allow_remote_control yes
listen_on unix:/tmp/kitty
enable_audio_bell no
clipboard_control write-clipboard write-primary read-clipboard read-primary
# keyboard shortcuts
map ctrl+shift+,   load_config_file
map ctrl+shift+t   launch --type=background ~/.config/kitty/scripts/toggle_cursor_trail.sh
