# NOTE: ==== options ====
set -g allow-rename on
setw -g mode-keys vi
set -g mouse on
set -g default-terminal "tmux-256color"
set -ga terminal-features ",*:RGB"
set -g base-index 1
set -g pane-base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -sg escape-time 0
set -g repeat-time 1000
set -g status-interval 1
set -g detach-on-destroy off
set -g history-limit 40000
set -g set-clipboard on
# NOTE: ==== bindings ====
unbind C-b
set -g prefix C-space
bind C-space send-prefix
# panes
bind '\' split-pane -h -c "#{pane_current_path}"
bind '-' split-pane -v -c "#{pane_current_path}"
# pane navigation
bind -n 'M-h' select-pane -L
bind -n 'M-j' select-pane -D
bind -n 'M-k' select-pane -U
bind -n 'M-l' select-pane -R
# pane resize
bind -n 'M-H' resize-pane -L 5
bind -n 'M-J' resize-pane -D 2
bind -n 'M-K' resize-pane -U 2
bind -n 'M-L' resize-pane -R 5
# windows
bind 'c' new-window -c "#{pane_current_path}"
# sessions
bind 'C-k' command-prompt -p "New session:" "new-session -A -s '%%'"
# closing
bind 'x' kill-pane
bind 'w' kill-window
bind 'q' kill-session
# reload config
bind 'r' source-file ~/.config/tmux/tmux.conf
# show/hide status bar
bind 'o' set-option -g status
# vim keys
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

# NOTE: ==== scripts ====
bind -n 'C-s' popup -w 50% -h 60% -T " Sessionizer " -E "~/scripts/tmux/sessionizer.sh"
bind 'C-l' popup -d "#{pane_current_path}" -w 95% -h 90% -T " LazyGit " -E "lazygit"
# NOTE: ==== visual styling ====
white=#d0d0d0
grey=#505050
bg=#141414
# vim mode
setw -g mode-style 'fg=#101010 bg=#c09070 bold'
# panes
set -g pane-border-style "fg=#242424"
set -g pane-active-border-style "fg=${grey}"
# status bar
set -g status-position bottom
set -g status-style "fg=${white} bg=${bg} nobold"
set -g status-justify absolute-centre
set -g window-status-separator "  "
set -g status-left-length 100
set -g status-right-length 100
# NOTE: left
# session name
set -g status-left ""
set -ga status-left "#[fg=${white} bold]#S"
# NOTE: center
# current window
set -g window-status-current-style "fg=${white} bold"
set -g window-status-current-format "#I:#W#F"
# other windows
set -g window-status-style "fg=${grey} nobold"
set -g window-status-format "#I:#W#F"
# NOTE: right
# host name
set -g status-right ""
set -ga status-right "#[fg=${grey} nobold]#H"
# NOTE: messages
set -g message-style 'fg=#c08060 bold'
