console_title_template = "{{ .Shell }} in {{ .Folder }}"
version = 3
final_space = true

## FIRST LINE
[[blocks]]
type = "prompt"
alignment = "left"
newline = true

## PATH
[[blocks.segments]]
type = "path"
style = "plain"
foreground = "p:purple"
background = "transparent"
template = "<b>{{ .Path }} </b>"

[blocks.segments.properties]
left_format = "󰉋 %s"
style = "full"

## GIT STATUS
[[blocks.segments]]
type = "git"
style = "plain"
foreground = "p:grey"
background = "transparent"
template = "on <p:blue><b>{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}<p:red>*{{ end }}</b> "

[blocks.segments.properties]
fetch_status = true

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

## PROMPT SYMBOL
[[blocks.segments]]
type = "text"
style = "plain"
foreground = "p:purple"
background = "p:transparent"
template = "<p:purple>❱"

[transient_prompt]
foreground = "p:purple2"
background = "transparent"
template = "❯ "

[palette]
grey = "#808080"
red = "#EF5F5F"
blue = "#5955C7"
purple = "#A957CE"
purple2 = "#5D3E6A"
black = "#000000"
