console_title_template = "{{ .Shell }}"
version = 3
final_space = true

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "path"
  style = "plain"
  background = "transparent"
  foreground = "p:purple"
  template = "󰉋 {{ .Path }} "

    [blocks.segments.properties]
    style = "full"

  [[blocks.segments]]
  type = "git"
  style = "plain"
  background = "transparent"
  foreground = "p:light_grey"
  template = "on <p:light_blue>{{ .HEAD }}</>{{ if or (.Working.Changed) (.Staging.Changed) }}<p:red>*</>{{ end }} "

    [blocks.segments.properties]
    fetch_status = true
  
[[blocks]]
type = "prompt"
alignment = "right"

  [[blocks.segments]]
  type = "executiontime"
  style = "plain"
  background = "transparent"
  foreground = "p:dark_grey"
  template = "in {{.FormattedMs}}    "

    [blocks.segments.properties]
    always_enabled = true
    style = "austin"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "text"
  style = "plain"
  background = "transparent"
  foreground = "p:blue"
  template = "λ"

[secondary_prompt]
background = "transparent"
foreground = "p:blue"
template = "λ "

[transient_prompt]
background = "transparent"
foreground = "p:blue"
template = "λ "

[palette]
light_grey = "#707070"
dark_grey = "#404040"
red = "#D04952"
light_blue = "#4D79E8"
blue = "#916FE8"
purple = "#BE70E2"
