format = """
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

add_newline = true

palette = "main"

[palettes.main]
color_grey = "#808080"
color_red = "#EF5F5F"
color_blue = "#5955C7"
color_purple = "#A957CE"

[directory]
format = "[󰉋 $path]($style)[$read_only]($read_only_style)"
style = "bold color_purple"

[git_branch]
format = " [on](color_grey) [$symbol$branch(:$remote_branch)]($style)"
style = "bold color_blue"

[git_status]
format = "[$modified]($style)"
modified = "*"
style = "bold color_red"

[character]
format = "$symbol "
success_symbol = "[❱](color_purple)"
error_symbol = "[❱](color_red)"
